/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogo;

import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class JFrame_Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Principal.class.getName());

    /**
     * Creates new form JFrame_Principal
     */
    public JFrame_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Ghost1 = new javax.swing.JButton();
        jButton_Ghost2 = new javax.swing.JButton();
        jButton_Fruta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Ghost1.setText("1 👻 1");
        jButton_Ghost1.setFocusable(false);
        jButton_Ghost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Ghost1ActionPerformed(evt);
            }
        });

        jButton_Ghost2.setText("2 👻 2");
        jButton_Ghost2.setFocusable(false);

        jButton_Fruta.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Fruta.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Fruta.setText("🍓");
        jButton_Fruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_FrutaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jButton_Fruta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jButton_Ghost2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton_Ghost1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Ghost1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jButton_Fruta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Ghost2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Ghost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Ghost1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Ghost1ActionPerformed

    private void jButton_FrutaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_FrutaKeyPressed
        switch (evt.getKeyCode()) {
            case 38:
                new Thread (){
                    @Override
                    public void run(){
                         Movimenta.cima(jButton_Ghost1);
                    }
                }.start();
                
                break;
               
            case 40:
                new Thread () {
                    @Override
                    public void run() {
                        Movimenta.baixo(jButton_Ghost1, JFrame_Principal.this);
                }
            }.start();
                break;
            case 37:
                Movimenta.esquerda(jButton_Ghost1);
                break;
            case 39:
                Movimenta.direita(jButton_Ghost1, this);
                break;
            default:
                throw new AssertionError();
            case 87:
                new Thread () {
                    @Override
                    public void run() {
                       Movimenta.cima(jButton_Ghost2); 
                    }
                }.start();
                break;
            case 83:
                Movimenta.baixo(jButton_Ghost2, this);
                break;
            case 65:
                Movimenta.esquerda(jButton_Ghost2);
                break;
            case 68:
                Movimenta.direita(jButton_Ghost2, this);
                break;
        }
        
        if (jButton_Ghost1.getBounds().intersects(jButton_Fruta.getBounds())) {
            Movimenta.sorteiaPosicao(jButton_Fruta, this);
        }
        if (jButton_Ghost2.getBounds().intersects(jButton_Fruta.getBounds())) {
            Movimenta.sorteiaPosicao(jButton_Fruta, this);
        }
    }//GEN-LAST:event_jButton_FrutaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Fruta;
    private javax.swing.JButton jButton_Ghost1;
    private javax.swing.JButton jButton_Ghost2;
    // End of variables declaration//GEN-END:variables
}
